import { SupportedNetworks, Network, SupportedAMM, AMM } from "./types";
import {
  arbitrum,
  polygon,
  mainnet,
  avalanche,
  moonriver,
  fantom,
} from "assets/networks";

export const NETWORKS: {
  [key: number]: Network;
} = {
  1: {
    name: "Mainnet",
    rpcUrl: process.env.RPC_URL_1!,
    infoPageUrl: "https://etherscan.io/tx/",
    infoPage: "Etherscan",
    logo: mainnet,
    backgroundColor: "#364683",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "",
    nativeToken: "eth",
  },
  42161: {
    name: "Arbitrum",
    rpcUrl: process.env.RPC_URL_42161!,
    infoPageUrl: "https://arbiscan.io/tx/",
    infoPage: "Arbiscan",
    logo: arbitrum,
    backgroundColor: "#23A9C7",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "https://arb1.arbitrum.io/rpc",
    nativeToken: "eth",
  },
  137: {
    name: "Polygon",
    rpcUrl: process.env.RPC_URL_137!,
    infoPageUrl: "https://polygonscan.com/tx/",
    infoPage: "Polygonscan",
    logo: polygon,
    backgroundColor: "#8D49FF",
    defaultTokenSymbol: "MATIC",
    publicRpcUrl: "https://rpc-mainnet.maticvigil.com/",
    nativeToken: "matic",
  },
  43114: {
    name: "Avalanche",
    rpcUrl: process.env.RPC_URL_43114!,
    infoPageUrl: "https://cchain.explorer.avax.network/tx/",
    infoPage: "Avax Scan",
    logo: avalanche,
    backgroundColor: "#C73738",
    defaultTokenSymbol: "AVAX",
    publicRpcUrl: "https://api.avax.network/ext/bc/C/rpc",
    nativeToken: "avax",
  },
  3: {
    name: "Ropsten",
    rpcUrl: process.env.RPC_URL_3!,
    infoPageUrl: "https://ropsten.etherscan.io/tx/",
    infoPage: "Etherscan",
    logo: mainnet,
    backgroundColor: "#364683",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "",
    nativeToken: "eth",
  },
  80001: {
    name: "Mumbai",
    rpcUrl: process.env.RPC_URL_80001!,
    infoPageUrl: "https://mumbai.polygonscan.com/tx/",
    infoPage: "Polygonscan",
    logo: polygon,
    backgroundColor: "#8D49FF",
    defaultTokenSymbol: "MATIC",
    publicRpcUrl: "https://rpc-mumbai.maticvigil.com/",
    nativeToken: "matic",
  },
  421611: {
    name: "Rinkeby",
    rpcUrl: process.env.RPC_URL_421611!,
    infoPageUrl: "https://rinkeby-explorer.arbitrum.io/tx/",
    infoPage: "Arbitrum.io",
    logo: arbitrum,
    backgroundColor: "#23A9C7",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "https://rinkeby.arbitrum.io/rpc",
    nativeToken: "eth",
  },
  1285: {
    name: "Moonriver",
    rpcUrl: process.env.RPC_URL_1285!,
    infoPageUrl: "https://blockscout.moonriver.moonbeam.network/tx/",
    infoPage: "Moonriver Blockscout",
    logo: moonriver,
    backgroundColor: "#F3B406",
    defaultTokenSymbol: "MOVR",
    publicRpcUrl: "https://rpc.moonriver.moonbeam.network",
    nativeToken: "movr",
  },
  250: {
    name: "Fantom",
    rpcUrl: process.env.RPC_URL_250!,
    infoPageUrl: "https://ftmscan.com/tx/",
    infoPage: "Fantom Scan",
    logo: fantom,
    backgroundColor: "#4172CC",
    defaultTokenSymbol: "FTM",
    publicRpcUrl: "https://rpc.ftm.tools",
    nativeToken: "ftm",
  },
  4: {
    name: "Rinkeby",
    rpcUrl: process.env.RPC_URL_4!,
    infoPageUrl: "https://rinkeby-explorer.etherium.io/tx/",
    infoPage: "Rinkeby.io",
    logo: arbitrum,
    backgroundColor: "#23A9C7",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "https://rinkeby.etherium.io/rpc",
    nativeToken: "eth",
  },
  42: {
    name: "Kovan",
    rpcUrl: process.env.RPC_URL_42!,
    infoPageUrl: "https://kovan-explorer.etherium.io/tx/",
    infoPage: "kovan.io",
    logo: arbitrum,
    backgroundColor: "#23A9C7",
    defaultTokenSymbol: "ETH",
    publicRpcUrl: "https://kovan.etherium.io/rpc",
    nativeToken: "eth",
  },
};

export const AMMS: {
  [ammId in SupportedAMM]: AMM;
} = {
  uniswap: {
    name: "Uniswap",
    logo: 'uniswap',
  },
  sushiswap: {
    name: "SushiSwap",
    logo: 'sushiswap',
  },
  quickswap: {
    name: "QuickSwap",
    logo: 'quickswap',
  }
}